ep: ep
epp: epp
vienna: vienna
jstor: jstor
utc: utc
edn: edn
doi: doi
http: http
https: https
downloaded: downloaded
doi: doi
ab: ab
aber: aber
alle: alle
allem: allem
allen: allen
aller: aller
alles: alles
als: als
also: also
am: am
an: an
ander: ander
andere: andere
anderem: anderem
anderen: anderen
anderer: anderer
anderes: anderes
anderm: anderm
andern: andern
anders: anders
auch: auch
auf: auf
aus: aus
bei: bei
bereits: bereits
bin: bin
bis: bis
bist: bist
da: da
dabei: dabei
daher: daher
dar: dar
damit: damit
dann: dann
das: das
dass: dass
dasselbe: dasselbe
dazu: dazu
daß: daß
dein: dein
deine: deine
deinem: deinem
deinen: deinen
deiner: deiner
deines: deines
dem: dem
demselben: demselben
den: den
denen: denen
derer: derer
denn: denn
denselben: denselben
der: der
derer: derer
derselbe: derselbe
derselben: derselben
des: des
deshalb: deshalb
desselben: desselben
dessen: dessen
dich: dich
die: die
dies: dies
diese: diese
dieselbe: dieselbe
dieselben: dieselben
diesem: diesem
diesen: diesen
dieser: dieser
dieses: dieses
dir: dir
doch: doch
dort: dort
du: du
durch: durch
ein: ein
eine: eine
einem: einem
einen: einen
einer: einer
eines: eines
einig: einig
einige: einige
einigem: einigem
einigen: einigen
einiger: einiger
einiges: einiges
einmal: einmal
er: er
erst: erst
es: es
etwa: etwa
etwas: etwas
euch: euch
euer: euer
eure: eure
eurem: eurem
euren: euren
eurer: eurer
eures: eures
für: für
gegen: gegen
gerade: gerade
gewesen: gewesen
hab: hab
habe: habe
haben: haben
hat: hat
hatte: hatte
hatten: hatten
hier: hier
hin: hin
hinter: hinter
ich: ich
ihm: ihm
ihn: ihn
ihnen: ihnen
ihr: ihr
ihre: ihre
ihrem: ihrem
ihren: ihren
ihrer: ihrer
ihres: ihres
im: im
in: in
indem: indem
ins: ins
ist: ist
jede: jede
jedem: jedem
jeden: jeden
jeder: jeder
jedes: jedes
jedoch: jedoch
jene: jene
jenem: jenem
jenen: jenen
jener: jener
jenes: jenes
jetzt: jetzt
kann: kann
kaum: kaum
kein: kein
keine: keine
keinem: keinem
keinen: keinen
keiner: keiner
keines: keines
konnte: konnte
können: können
könnte: könnte
machen: machen
man: man
manche: manche
manchem: manchem
manchen: manchen
mancher: mancher
manches: manches
mein: mein
meine: meine
meinem: meinem
meinen: meinen
meiner: meiner
meines: meines
mich: mich
mir: mir
mit: mit
muss: muss
musste: musste
nach: nach
neben: neben
nicht: nicht
nichts: nichts
noch: noch
nun: nun
nur: nur
ob: ob
oder: oder
ohne: ohne
sehr: sehr
sei: sei
sein: sein
seine: seine
seinem: seinem
seinen: seinen
seiner: seiner
seines: seines
selbst: selbst
sich: sich
sie: sie
sind: sind
so: so
sogar: sogar
solche: solche
solchem: solchem
solchen: solchen
solcher: solcher
solches: solches
soll: soll
sollte: sollte
sondern: sondern
sonst: sonst
sowie: sowie
um: um
und: und
uns: uns
unser: unser
unsere: unsere
unserem: unserem
unseren: unseren
unserer: unserer
unseres: unseres
unter: unter
viel: viel
vom: vom
von: von
vor: vor
war: war
waren: waren
warst: warst
was: was
weg: weg
weil: weil
weiter: weiter
welche: welche
welchem: welchem
welchen: welchen
welcher: welcher
welches: welches
wenn: wenn
werde: werde
werden: werden
wie: wie
wieder: wieder
will: will
wir: wir
wird: wird
wirst: wirst
wo: wo
wollen: wollen
wollte: wollte
worden: worden
während: während
wurde: wurde
würde: würde
würden: würden
zu: zu
zum: zum
zur: zur
zwar: zwar
zwischen: zwischen
über: über
\'ll: \'ll
\'tis: \'tis
\'twas: \'twas
\'ve: \'ve
a: a
a: a's
able: able
ableabout: ableabout
about: about
above: above
abroad: abroad
abst: abst
accordance: accordance
according: according
accordingly: accordingly
across: across
act: act
actually: actually
ad: ad
added: added
adj: adj
adopted: adopted
ae: ae
af: af
affected: affected
affecting: affecting
affects: affects
after: after
afterwards: afterwards
ag: ag
again: again
against: against
ago: ago
ah: ah
ahead: ahead
ai: ai
ain: ain't
aint: aint
al: al
all: all
allow: allow
allows: allows
almost: almost
alone: alone
along: along
alongside: alongside
already: already
also: also
although: although
always: always
am: am
amid: amid
amidst: amidst
among: among
amongst: amongst
amoungst: amoungst
amount: amount
an: an
and: and
announce: announce
another: another
any: any
anybody: anybody
anyhow: anyhow
anymore: anymore
anyone: anyone
anything: anything
anyway: anyway
anyways: anyways
anywhere: anywhere
ao: ao
apart: apart
apparently: apparently
appear: appear
appreciate: appreciate
appropriate: appropriate
approximately: approximately
aq: aq
ar: ar
are: are
area: area
areas: areas
aren: aren
aren: aren't
arent: arent
arise: arise
around: around
arpa: arpa
as: as
aside: aside
ask: ask
asked: asked
asking: asking
asks: asks
associated: associated
at: at
au: au
auth: auth
available: available
aw: aw
away: away
awfully: awfully
az: az
b: b
ba: ba
back: back
backed: backed
backing: backing
backs: backs
backward: backward
backwards: backwards
bb: bb
bd: bd
be: be
became: became
because: because
become: become
becomes: becomes
becoming: becoming
been: been
before: before
beforehand: beforehand
began: began
begin: begin
beginning: beginning
beginnings: beginnings
begins: begins
behind: behind
being: being
beings: beings
believe: believe
below: below
beside: beside
besides: besides
best: best
better: better
between: between
beyond: beyond
bf: bf
bg: bg
bh: bh
bi: bi
big: big
bill: bill
billion: billion
biol: biol
bj: bj
bm: bm
bn: bn
bo: bo
both: both
bottom: bottom
br: br
brief: brief
briefly: briefly
bs: bs
bt: bt
but: but
buy: buy
bv: bv
bw: bw
by: by
bz: bz
c: c
c: c'mon
c: c's
ca: ca
call: call
came: came
can: can
can: can't
cannot: cannot
cant: cant
caption: caption
case: case
cases: cases
cause: cause
causes: causes
cc: cc
cd: cd
certain: certain
certainly: certainly
cf: cf
cg: cg
ch: ch
changes: changes
ci: ci
ck: ck
cl: cl
clear: clear
clearly: clearly
click: click
cm: cm
cmon: cmon
cn: cn
co: co
co: co.
com: com
come: come
comes: comes
computer: computer
con: con
concerning: concerning
consequently: consequently
consider: consider
considering: considering
contain: contain
containing: containing
contains: contains
copy: copy
corresponding: corresponding
could: could
could: could've
couldn: couldn
couldn: couldn't
couldnt: couldnt
course: course
cr: cr
cry: cry
cs: cs
cu: cu
currently: currently
cv: cv
cx: cx
cy: cy
cz: cz
d: d
dare: dare
daren: daren't
darent: darent
date: date
de: de
dear: dear
definitely: definitely
describe: describe
described: described
despite: despite
detail: detail
did: did
didn: didn
didn: didn't
didnt: didnt
differ: differ
different: different
differently: differently
directly: directly
dj: dj
dk: dk
dm: dm
do: do
does: does
doesn: doesn
doesn: doesn't
doesnt: doesnt
doing: doing
don: don
don: don't
done: done
dont: dont
doubtful: doubtful
down: down
downed: downed
downing: downing
downs: downs
downwards: downwards
due: due
during: during
dz: dz
e: e
each: each
early: early
ec: ec
ed: ed
edu: edu
ee: ee
effect: effect
eg: eg
eh: eh
eight: eight
eighty: eighty
either: either
eleven: eleven
else: else
elsewhere: elsewhere
empty: empty
end: end
ended: ended
ending: ending
ends: ends
enough: enough
entirely: entirely
er: er
es: es
especially: especially
et: et
et: et-al
etc: etc
even: even
evenly: evenly
ever: ever
evermore: evermore
every: every
everybody: everybody
everyone: everyone
everything: everything
everywhere: everywhere
ex: ex
exactly: exactly
example: example
except: except
f: f
face: face
faces: faces
fact: fact
facts: facts
fairly: fairly
far: far
farther: farther
felt: felt
few: few
fewer: fewer
ff: ff
fi: fi
fifteen: fifteen
fifth: fifth
fifty: fifty
fify: fify
fill: fill
find: find
finds: finds
fire: fire
first: first
five: five
fix: fix
fj: fj
fk: fk
fm: fm
fo: fo
followed: followed
following: following
follows: follows
for: for
forever: forever
former: former
formerly: formerly
forth: forth
forty: forty
forward: forward
found: found
four: four
fr: fr
free: free
from: from
front: front
full: full
fully: fully
further: further
furthered: furthered
furthering: furthering
furthermore: furthermore
furthers: furthers
fx: fx
g: g
ga: ga
gave: gave
gb: gb
gd: gd
ge: ge
general: general
generally: generally
get: get
gets: gets
getting: getting
gf: gf
gg: gg
gh: gh
gi: gi
give: give
given: given
gives: gives
giving: giving
gl: gl
gm: gm
gmt: gmt
gn: gn
go: go
goes: goes
going: going
gone: gone
good: good
goods: goods
got: got
gotten: gotten
gov: gov
gp: gp
gq: gq
gr: gr
great: great
greater: greater
greatest: greatest
greetings: greetings
group: group
grouped: grouped
grouping: grouping
groups: groups
gs: gs
gt: gt
gu: gu
gw: gw
gy: gy
h: h
had: had
hadn: hadn't
hadnt: hadnt
half: half
happens: happens
hardly: hardly
has: has
hasn: hasn
hasn: hasn't
hasnt: hasnt
have: have
haven: haven
haven: haven't
havent: havent
having: having
he: he
he: he'd
he: he'll
he: he's
hed: hed
hell: hell
hello: hello
help: help
hence: hence
her: her
here: here
here: here's
hereafter: hereafter
hereby: hereby
herein: herein
heres: heres
hereupon: hereupon
hers: hers
herself: herself
herse: herse”
hes: hes
hi: hi
hid: hid
high: high
higher: higher
highest: highest
him: him
himself: himself
himse: himse”
his: his
hither: hither
hk: hk
hm: hm
hn: hn
home: home
homepage: homepage
hopefully: hopefully
how: how
how: how'd
how: how'll
how: how's
howbeit: howbeit
however: however
hr: hr
ht: ht
htm: htm
html: html
http: http
hu: hu
hundred: hundred
i: i
i: i'd
i: i'll
i: i'm
i: i've
i: i.e.
id: id
ie: ie
if: if
ignored: ignored
ii: ii
il: il
ill: ill
im: im
immediate: immediate
immediately: immediately
importance: importance
important: important
in: in
inasmuch: inasmuch
inc: inc
inc: inc.
indeed: indeed
index: index
indicate: indicate
indicated: indicated
indicates: indicates
information: information
inner: inner
inside: inside
insofar: insofar
instead: instead
int: int
interest: interest
interested: interested
interesting: interesting
interests: interests
into: into
invention: invention
inward: inward
io: io
iq: iq
ir: ir
is: is
isn: isn
isn: isn't
isnt: isnt
it: it
it: it'd
it: it'll
it: it's
itd: itd
itll: itll
its: its
itself: itself
itse: itse”
ive: ive
j: j
je: je
jm: jm
jo: jo
join: join
jp: jp
just: just
k: k
ke: ke
keep: keep
keeps: keeps
kept: kept
keys: keys
kg: kg
kh: kh
ki: ki
kind: kind
km: km
kn: kn
knew: knew
know: know
known: known
knows: knows
kp: kp
kr: kr
kw: kw
ky: ky
kz: kz
l: l
la: la
large: large
largely: largely
last: last
lately: lately
later: later
latest: latest
latter: latter
latterly: latterly
lb: lb
lc: lc
least: least
length: length
less: less
lest: lest
let: let
let: let's
lets: lets
li: li
like: like
liked: liked
likely: likely
likewise: likewise
line: line
little: little
lk: lk
ll: ll
long: long
longer: longer
longest: longest
look: look
looking: looking
looks: looks
low: low
lower: lower
lr: lr
ls: ls
lt: lt
ltd: ltd
lu: lu
lv: lv
ly: ly
m: m
ma: ma
made: made
mainly: mainly
make: make
makes: makes
making: making
man: man
many: many
may: may
maybe: maybe
mayn: mayn't
maynt: maynt
mc: mc
md: md
me: me
mean: mean
means: means
meantime: meantime
meanwhile: meanwhile
member: member
members: members
men: men
merely: merely
mg: mg
mh: mh
microsoft: microsoft
might: might
might: might've
mightn: mightn't
mightnt: mightnt
mil: mil
mill: mill
million: million
mine: mine
minus: minus
miss: miss
mk: mk
ml: ml
mm: mm
mn: mn
mo: mo
more: more
moreover: moreover
most: most
mostly: mostly
move: move
mp: mp
mq: mq
mr: mr
mrs: mrs
ms: ms
msie: msie
mt: mt
mu: mu
much: much
mug: mug
must: must
must: must've
mustn: mustn't
mustnt: mustnt
mv: mv
mw: mw
mx: mx
my: my
myself: myself
myse: myse”
mz: mz
n: n
na: na
name: name
namely: namely
nay: nay
nc: nc
nd: nd
ne: ne
near: near
nearly: nearly
necessarily: necessarily
necessary: necessary
need: need
needed: needed
needing: needing
needn: needn't
neednt: neednt
needs: needs
neither: neither
net: net
netscape: netscape
never: never
neverf: neverf
neverless: neverless
nevertheless: nevertheless
new: new
newer: newer
newest: newest
next: next
nf: nf
ng: ng
ni: ni
nine: nine
ninety: ninety
nl: nl
no: no
no: no-one
nobody: nobody
non: non
none: none
nonetheless: nonetheless
noone: noone
nor: nor
normally: normally
nos: nos
not: not
noted: noted
nothing: nothing
notwithstanding: notwithstanding
novel: novel
now: now
nowhere: nowhere
np: np
nr: nr
nu: nu
null: null
number: number
numbers: numbers
nz: nz
o: o
obtain: obtain
obtained: obtained
obviously: obviously
of: of
off: off
often: often
oh: oh
ok: ok
okay: okay
old: old
older: older
oldest: oldest
om: om
omitted: omitted
on: on
once: once
one: one
one: one's
ones: ones
only: only
onto: onto
open: open
opened: opened
opening: opening
opens: opens
opposite: opposite
or: or
ord: ord
order: order
ordered: ordered
ordering: ordering
orders: orders
org: org
other: other
others: others
otherwise: otherwise
ought: ought
oughtn: oughtn't
oughtnt: oughtnt
our: our
ours: ours
ourselves: ourselves
out: out
outside: outside
over: over
overall: overall
owing: owing
own: own
p: p
pa: pa
page: page
pages: pages
part: part
parted: parted
particular: particular
particularly: particularly
parting: parting
parts: parts
past: past
pe: pe
per: per
perhaps: perhaps
pf: pf
pg: pg
ph: ph
pk: pk
pl: pl
place: place
placed: placed
places: places
please: please
plus: plus
pm: pm
pmid: pmid
pn: pn
point: point
pointed: pointed
pointing: pointing
points: points
poorly: poorly
possible: possible
possibly: possibly
potentially: potentially
pp: pp
pr: pr
predominantly: predominantly
present: present
presented: presented
presenting: presenting
presents: presents
presumably: presumably
previously: previously
primarily: primarily
probably: probably
problem: problem
problems: problems
promptly: promptly
proud: proud
provided: provided
provides: provides
pt: pt
put: put
puts: puts
pw: pw
py: py
q: q
qa: qa
que: que
quickly: quickly
quite: quite
qv: qv
r: r
ran: ran
rather: rather
rd: rd
re: re
readily: readily
really: really
reasonably: reasonably
recent: recent
recently: recently
ref: ref
refs: refs
regarding: regarding
regardless: regardless
regards: regards
related: related
relatively: relatively
research: research
reserved: reserved
respectively: respectively
resulted: resulted
resulting: resulting
results: results
right: right
ring: ring
ro: ro
room: room
rooms: rooms
round: round
ru: ru
run: run
rw: rw
s: s
sa: sa
said: said
same: same
saw: saw
say: say
saying: saying
says: says
sb: sb
sc: sc
sd: sd
se: se
sec: sec
second: second
secondly: secondly
seconds: seconds
section: section
see: see
seeing: seeing
seem: seem
seemed: seemed
seeming: seeming
seems: seems
seen: seen
sees: sees
self: self
selves: selves
sensible: sensible
sent: sent
serious: serious
seriously: seriously
seven: seven
seventy: seventy
several: several
sg: sg
sh: sh
shall: shall
shan: shan't
shant: shant
she: she
she: she'd
she: she'll
she: she's
shed: shed
shell: shell
shes: shes
should: should
should: should've
shouldn: shouldn
shouldn: shouldn't
shouldnt: shouldnt
show: show
showed: showed
showing: showing
shown: shown
showns: showns
shows: shows
si: si
side: side
sides: sides
significant: significant
significantly: significantly
similar: similar
similarly: similarly
since: since
sincere: sincere
site: site
six: six
sixty: sixty
sj: sj
sk: sk
sl: sl
slightly: slightly
sm: sm
small: small
smaller: smaller
smallest: smallest
sn: sn
so: so
some: some
somebody: somebody
someday: someday
somehow: somehow
someone: someone
somethan: somethan
something: something
sometime: sometime
sometimes: sometimes
somewhat: somewhat
somewhere: somewhere
soon: soon
sorry: sorry
specifically: specifically
specified: specified
specify: specify
specifying: specifying
sr: sr
st: st
state: state
states: states
still: still
stop: stop
strongly: strongly
su: su
sub: sub
substantially: substantially
successfully: successfully
such: such
sufficiently: sufficiently
suggest: suggest
sup: sup
sure: sure
sv: sv
sy: sy
system: system
sz: sz
t: t
t: t's
take: take
taken: taken
taking: taking
tc: tc
td: td
tell: tell
ten: ten
tends: tends
test: test
text: text
tf: tf
tg: tg
th: th
than: than
thank: thank
thanks: thanks
thanx: thanx
that: that
that: that'll
that: that's
that: that've
thatll: thatll
thats: thats
thatve: thatve
the: the
their: their
theirs: theirs
them: them
themselves: themselves
then: then
thence: thence
there: there
there: there'd
there: there'll
there: there're
there: there's
there: there've
thereafter: thereafter
thereby: thereby
thered: thered
therefore: therefore
therein: therein
therell: therell
thereof: thereof
therere: therere
theres: theres
thereto: thereto
thereupon: thereupon
thereve: thereve
these: these
they: they
they: they'd
they: they'll
they: they're
they: they've
theyd: theyd
theyll: theyll
theyre: theyre
theyve: theyve
thick: thick
thin: thin
thing: thing
things: things
think: think
thinks: thinks
third: third
thirty: thirty
this: this
thorough: thorough
thoroughly: thoroughly
those: those
thou: thou
though: though
thoughh: thoughh
thought: thought
thoughts: thoughts
thousand: thousand
three: three
throug: throug
through: through
throughout: throughout
thru: thru
thus: thus
til: til
till: till
tip: tip
tis: tis
tj: tj
tk: tk
tm: tm
tn: tn
to: to
today: today
together: together
too: too
took: took
top: top
toward: toward
towards: towards
tp: tp
tr: tr
tried: tried
tries: tries
trillion: trillion
truly: truly
try: try
trying: trying
ts: ts
tt: tt
turn: turn
turned: turned
turning: turning
turns: turns
tv: tv
tw: tw
twas: twas
twelve: twelve
twenty: twenty
twice: twice
two: two
tz: tz
u: u
ua: ua
ug: ug
uk: uk
um: um
un: un
under: under
underneath: underneath
undoing: undoing
unfortunately: unfortunately
unless: unless
unlike: unlike
unlikely: unlikely
until: until
unto: unto
up: up
upon: upon
ups: ups
upwards: upwards
us: us
use: use
used: used
useful: useful
usefully: usefully
usefulness: usefulness
uses: uses
using: using
usually: usually
uucp: uucp
uy: uy
uz: uz
v: v
va: va
value: value
various: various
vc: vc
ve: ve
versus: versus
very: very
vg: vg
vi: vi
via: via
viz: viz
vn: vn
vol: vol
vols: vols
vs: vs
vu: vu
w: w
want: want
wanted: wanted
wanting: wanting
wants: wants
was: was
wasn: wasn
wasn: wasn't
wasnt: wasnt
way: way
ways: ways
we: we
we: we'd
we: we'll
we: we're
we: we've
web: web
webpage: webpage
website: website
wed: wed
welcome: welcome
well: well
wells: wells
went: went
were: were
weren: weren
weren: weren't
werent: werent
weve: weve
wf: wf
what: what
what: what'd
what: what'll
what: what's
what: what've
whatever: whatever
whatll: whatll
whats: whats
whatve: whatve
when: when
when: when'd
when: when'll
when: when's
whence: whence
whenever: whenever
where: where
where: where'd
where: where'll
where: where's
whereafter: whereafter
whereas: whereas
whereby: whereby
wherein: wherein
wheres: wheres
whereupon: whereupon
wherever: wherever
whether: whether
which: which
whichever: whichever
while: while
whilst: whilst
whim: whim
whither: whither
who: who
who: who'd
who: who'll
who: who's
whod: whod
whoever: whoever
whole: whole
wholl: wholl
whom: whom
whomever: whomever
whos: whos
whose: whose
why: why
why: why'd
why: why'll
why: why's
widely: widely
width: width
will: will
willing: willing
wish: wish
with: with
within: within
without: without
won: won
won: won't
wonder: wonder
wont: wont
words: words
work: work
worked: worked
working: working
works: works
world: world
would: would
would: would've
wouldn: wouldn
wouldn: wouldn't
wouldnt: wouldnt
ws: ws
www: www
x: x
y: y
ye: ye
year: year
years: years
yes: yes
yet: yet
you: you
you: you'd
you: you'll
you: you're
you: you've
youd: youd
youll: youll
young: young
younger: younger
youngest: youngest
your: your
youre: youre
yours: yours
yourself: yourself
yourselves: yourselves
youve: youve
yt: yt
yu: yu
z: z
za: za
zero: zero
zm: zm
doi: doi