path_to_memex: .\_data\
bib_all: .\_bib\\myBib.bib
bibtex_keys: .\_bib\\bibtex_keys.yml
language_keys: .\_bib\\bibtex_languages.yml
path_to_poppler: .\_poppler\bin\
defaultLang: "eng"
template_page: .\_template\template_page.html
template_index: .\_template\template_index.html
template_search: .\_template\template_search.html
content_index: .\_template\content_index.html
ngram_range: (1,1)
min_df: 5
max_df: 0.5
tfidf_publ: results_tfidf_publications.dataJson
publ_cosDist: results_cosineDist_publications.dataJson
page_cosDist: results_cosineDist_pages.dataJson
ocr_results: .json